spring.application.name=GetAPI

# 서버 포트 설정 (선택사항)
server.port=8080

# Google OAuth2 설정
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
#spring.security.oauth2.client.registration.google.redirect-uri=http:/localhost:8080/login/oauth2/code/google

# H2
spring.datasource.url=jdbc:h2:mem:getapi
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# JWT
jwt.secret-key=${JWT_SECRET_KEY}

# IMAP
imap.username=${IMAP_USERNAME}
imap.password=${IMAP_PASSWORD}

logging.level.org.springframework.security=DEBUG