spring.application.name=DevLib_project

# 서버 포트 설정 (선택사항)
server.port=8080

# Google OAuth2 설정
spring.security.oauth2.client.registration.google.client-id=1097186976907-dcbr2b1rkg4p17vdvl5c5q4osjlficfi.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
#spring.security.oauth2.client.registration.google.redirect-uri=http:/localhost:8080/login/oauth2/code/google

logging.level.org.springframework.security=DEBUG